package br.unesp.locadora.gui;

import br.unesp.locadora.gui.caracteristica.CaracteristicasForm;
import br.unesp.locadora.gui.categoria.CategoriasForm;
import br.unesp.locadora.gui.marca.MarcasForm;
import br.unesp.locadora.gui.cliente.ClientesForm;
import br.unesp.locadora.gui.cor.CoresForm;
import br.unesp.locadora.gui.fatura.FaturasForm;
import br.unesp.locadora.gui.modelo.ModelosForm;
import br.unesp.locadora.gui.pedido.PedidosForm;
import br.unesp.locadora.gui.veiculo.VeiculosForm;

public class EZManagerForm extends javax.swing.JFrame {

    /**
     * Creates new form EZManagerForm
     */
    public EZManagerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        faixa1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        linha1 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JLabel();
        btnPedidos = new javax.swing.JLabel();
        btnFaturas = new javax.swing.JLabel();
        linha2 = new javax.swing.JPanel();
        btnCategorias = new javax.swing.JLabel();
        btnMarcas = new javax.swing.JLabel();
        btnModelos = new javax.swing.JLabel();
        linha3 = new javax.swing.JPanel();
        btnCores = new javax.swing.JLabel();
        btnCaracteristicas = new javax.swing.JLabel();
        btnVeiculos = new javax.swing.JLabel();
        faixa2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EZ Manager");
        setExtendedState(6);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));

        faixa1.setBackground(new java.awt.Color(44, 62, 80));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N

        javax.swing.GroupLayout faixa1Layout = new javax.swing.GroupLayout(faixa1);
        faixa1.setLayout(faixa1Layout);
        faixa1Layout.setHorizontalGroup(
            faixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        faixa1Layout.setVerticalGroup(
            faixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        scroll.setBorder(null);

        panel.setLayout(new java.awt.GridLayout(3, 1));

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tile_clientes.png"))); // NOI18N
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });
        linha1.add(btnClientes);

        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tile_pedidos.png"))); // NOI18N
        btnPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPedidosMouseClicked(evt);
            }
        });
        linha1.add(btnPedidos);

        btnFaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tile_faturas.png"))); // NOI18N
        btnFaturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFaturasMouseClicked(evt);
            }
        });
        linha1.add(btnFaturas);

        panel.add(linha1);

        btnCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tile_categorias.png"))); // NOI18N
        btnCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategoriasMouseClicked(evt);
            }
        });
        linha2.add(btnCategorias);

        btnMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tile_marcas.png"))); // NOI18N
        btnMarcas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMarcasMouseClicked(evt);
            }
        });
        linha2.add(btnMarcas);

        btnModelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tile_modelos.png"))); // NOI18N
        btnModelos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModelosMouseClicked(evt);
            }
        });
        linha2.add(btnModelos);

        panel.add(linha2);

        btnCores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tile_cores.png"))); // NOI18N
        btnCores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCoresMouseClicked(evt);
            }
        });
        linha3.add(btnCores);

        btnCaracteristicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tile_caracteristicas.png"))); // NOI18N
        btnCaracteristicas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCaracteristicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCaracteristicasMouseClicked(evt);
            }
        });
        linha3.add(btnCaracteristicas);

        btnVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tile_veiculos.png"))); // NOI18N
        btnVeiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVeiculosMouseClicked(evt);
            }
        });
        linha3.add(btnVeiculos);

        panel.add(linha3);

        scroll.setViewportView(panel);

        faixa2.setBackground(new java.awt.Color(44, 62, 80));

        javax.swing.GroupLayout faixa2Layout = new javax.swing.GroupLayout(faixa2);
        faixa2.setLayout(faixa2Layout);
        faixa2Layout.setHorizontalGroup(
            faixa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        faixa2Layout.setVerticalGroup(
            faixa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(faixa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(faixa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(faixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faixa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        new ClientesForm().setVisible(true);
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidosMouseClicked
        new PedidosForm().setVisible(true);
    }//GEN-LAST:event_btnPedidosMouseClicked

    private void btnFaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFaturasMouseClicked
        new FaturasForm().setVisible(true);
    }//GEN-LAST:event_btnFaturasMouseClicked

    private void btnCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriasMouseClicked
        new CategoriasForm().setVisible(true);
    }//GEN-LAST:event_btnCategoriasMouseClicked

    private void btnMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarcasMouseClicked
        new MarcasForm().setVisible(true);
    }//GEN-LAST:event_btnMarcasMouseClicked

    private void btnModelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModelosMouseClicked
        new ModelosForm().setVisible(true);
    }//GEN-LAST:event_btnModelosMouseClicked

    private void btnCoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoresMouseClicked
        new CoresForm().setVisible(true);
    }//GEN-LAST:event_btnCoresMouseClicked

    private void btnCaracteristicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaracteristicasMouseClicked
        new CaracteristicasForm().setVisible(true);
    }//GEN-LAST:event_btnCaracteristicasMouseClicked

    private void btnVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeiculosMouseClicked
        new VeiculosForm().setVisible(true);
    }//GEN-LAST:event_btnVeiculosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EZManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EZManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EZManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EZManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EZManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCaracteristicas;
    private javax.swing.JLabel btnCategorias;
    private javax.swing.JLabel btnClientes;
    private javax.swing.JLabel btnCores;
    private javax.swing.JLabel btnFaturas;
    private javax.swing.JLabel btnMarcas;
    private javax.swing.JLabel btnModelos;
    private javax.swing.JLabel btnPedidos;
    private javax.swing.JLabel btnVeiculos;
    private javax.swing.JPanel faixa1;
    private javax.swing.JPanel faixa2;
    private javax.swing.JPanel linha1;
    private javax.swing.JPanel linha2;
    private javax.swing.JPanel linha3;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
