package br.unesp.locadora.gui.cliente;

import br.unesp.locadora.model.Cliente;
import br.unesp.locadora.model.Endereco;
import br.unesp.locadora.model.Fisica;
import br.unesp.locadora.model.Juridica;
import br.unesp.locadora.service.FisicaService;
import br.unesp.locadora.service.JuridicaService;
import br.unesp.locadora.util.CEP;
import java.time.ZoneId;
import javax.swing.JOptionPane;

public class AdicionarClienteForm extends javax.swing.JFrame {

    /**
     * Cliente pessoa física criado.
     */
    private Fisica clienteFisica;

    /**
     * Cliente pessoa jurídica criado.
     */
    private Juridica clienteJuridica;

    /**
     * Flag para fechar formulário.
     */
    private boolean fechar;

    /**
     * Serviço de persistência de clientes pessoa física.
     */
    FisicaService fisicaService = new FisicaService();

    /**
     * Serviço de persistência de clientes pessoa jurídica.
     */
    JuridicaService juridicaService = new JuridicaService();

    /**
     * Creates new form AdicionarClienteForm
     */
    public AdicionarClienteForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        faixa1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        painel1 = new javax.swing.JPanel();
        tabbed = new javax.swing.JTabbedPane();
        pnlFisica = new javax.swing.JPanel();
        scroll1 = new javax.swing.JScrollPane();
        painel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblRg = new javax.swing.JLabel();
        txtRg = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        txtNascimento = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        lblTelefone1 = new javax.swing.JLabel();
        txtTelefone1 = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        lblCep1 = new javax.swing.JLabel();
        txtCep1 = new javax.swing.JTextField();
        btnPesquisar1 = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        cbxEstado1 = new javax.swing.JComboBox<>();
        lblCidade1 = new javax.swing.JLabel();
        txtCidade1 = new javax.swing.JTextField();
        lblBairro1 = new javax.swing.JLabel();
        txtBairro1 = new javax.swing.JTextField();
        lblEndereco1 = new javax.swing.JLabel();
        txtEndereco1 = new javax.swing.JTextField();
        lblNumero1 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        lblComplemento1 = new javax.swing.JLabel();
        txtComplemento1 = new javax.swing.JTextField();
        painel3 = new javax.swing.JPanel();
        btnAdicionar1 = new javax.swing.JButton();
        btnSair1 = new javax.swing.JButton();
        pnlJuridica = new javax.swing.JPanel();
        scroll2 = new javax.swing.JScrollPane();
        painel4 = new javax.swing.JPanel();
        lblRazao = new javax.swing.JLabel();
        txtRazao = new javax.swing.JTextField();
        lblFantasia = new javax.swing.JLabel();
        txtFantasia = new javax.swing.JTextField();
        lblCnpj = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        lblIe = new javax.swing.JLabel();
        lblTelefone2 = new javax.swing.JLabel();
        txtTelefone2 = new javax.swing.JTextField();
        lblEmail2 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        lblCep2 = new javax.swing.JLabel();
        txtCep2 = new javax.swing.JTextField();
        btnPesquisar2 = new javax.swing.JButton();
        lblEstado2 = new javax.swing.JLabel();
        cbxEstado2 = new javax.swing.JComboBox<>();
        lblCidade2 = new javax.swing.JLabel();
        txtCidade2 = new javax.swing.JTextField();
        lblBairro2 = new javax.swing.JLabel();
        txtBairro2 = new javax.swing.JTextField();
        lblEndereco2 = new javax.swing.JLabel();
        txtEndereco2 = new javax.swing.JTextField();
        lblNumero2 = new javax.swing.JLabel();
        txtNumero2 = new javax.swing.JTextField();
        lblComplemento2 = new javax.swing.JLabel();
        txtComplemento2 = new javax.swing.JTextField();
        txtIe = new javax.swing.JTextField();
        painel5 = new javax.swing.JPanel();
        btnAdicionar2 = new javax.swing.JButton();
        btnSair2 = new javax.swing.JButton();
        faixa2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Cliente");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));

        faixa1.setBackground(new java.awt.Color(44, 62, 80));

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/title_cliente.png"))); // NOI18N

        javax.swing.GroupLayout faixa1Layout = new javax.swing.GroupLayout(faixa1);
        faixa1.setLayout(faixa1Layout);
        faixa1Layout.setHorizontalGroup(
            faixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        faixa1Layout.setVerticalGroup(
            faixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        painel1.setLayout(new java.awt.BorderLayout());

        pnlFisica.setLayout(new java.awt.BorderLayout());

        scroll1.setBorder(null);
        scroll1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lblNome.setText("Nome:");

        lblCpf.setText("CPF:");

        lblRg.setText("RG:");

        lblNascimento.setText("Data de Nascimento:");

        lblTelefone1.setText("Telefone:");

        lblEmail1.setText("E-mail:");

        lblCep1.setText("CEP:");

        btnPesquisar1.setText("Pesquisar");
        btnPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar1ActionPerformed(evt);
            }
        });

        lblEstado.setText("Estado:");

        cbxEstado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        lblCidade1.setText("Cidade:");

        lblBairro1.setText("Bairro:");

        lblEndereco1.setText("Endereço:");

        lblNumero1.setText("Número:");

        lblComplemento1.setText("Complemento:");

        javax.swing.GroupLayout painel2Layout = new javax.swing.GroupLayout(painel2);
        painel2.setLayout(painel2Layout);
        painel2Layout.setHorizontalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxEstado1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNome)
                    .addComponent(txtCpf)
                    .addComponent(txtRg)
                    .addComponent(txtNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelefone1)
                    .addComponent(txtEmail1)
                    .addGroup(painel2Layout.createSequentialGroup()
                        .addComponent(txtCep1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar1))
                    .addComponent(txtCidade1)
                    .addComponent(txtBairro1)
                    .addComponent(txtEndereco1)
                    .addComponent(txtNumero1)
                    .addGroup(painel2Layout.createSequentialGroup()
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblCpf)
                            .addComponent(lblRg)
                            .addComponent(lblNascimento)
                            .addComponent(lblTelefone1)
                            .addComponent(lblEmail1)
                            .addComponent(lblCep1)
                            .addComponent(lblEstado)
                            .addComponent(lblCidade1)
                            .addComponent(lblBairro1)
                            .addComponent(lblEndereco1)
                            .addComponent(lblNumero1)
                            .addComponent(lblComplemento1))
                        .addGap(0, 498, Short.MAX_VALUE))
                    .addComponent(txtComplemento1))
                .addContainerGap())
        );
        painel2Layout.setVerticalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelefone1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCep1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCidade1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBairro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndereco1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumero1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComplemento1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComplemento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scroll1.setViewportView(painel2);

        pnlFisica.add(scroll1, java.awt.BorderLayout.CENTER);

        painel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        btnAdicionar1.setText("Adicionar");
        btnAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar1ActionPerformed(evt);
            }
        });
        painel3.add(btnAdicionar1);

        btnSair1.setText("Sair");
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });
        painel3.add(btnSair1);

        pnlFisica.add(painel3, java.awt.BorderLayout.SOUTH);

        tabbed.addTab("Física", pnlFisica);

        pnlJuridica.setLayout(new java.awt.BorderLayout());

        scroll2.setBorder(null);
        scroll2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lblRazao.setText("Razão Social:");

        lblFantasia.setText("Nome Fantasia:");

        lblCnpj.setText("CNPJ:");

        lblIe.setText("Inscrição Estadual:");

        lblTelefone2.setText("Telefone:");

        lblEmail2.setText("E-mail:");

        lblCep2.setText("CEP:");

        btnPesquisar2.setText("Pesquisar");
        btnPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar2ActionPerformed(evt);
            }
        });

        lblEstado2.setText("Estado:");

        cbxEstado2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        lblCidade2.setText("Cidade:");

        lblBairro2.setText("Bairro:");

        lblEndereco2.setText("Endereço:");

        lblNumero2.setText("Número:");

        lblComplemento2.setText("Complemento:");

        javax.swing.GroupLayout painel4Layout = new javax.swing.GroupLayout(painel4);
        painel4.setLayout(painel4Layout);
        painel4Layout.setHorizontalGroup(
            painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxEstado2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRazao)
                    .addComponent(txtFantasia)
                    .addComponent(txtCnpj)
                    .addComponent(txtTelefone2)
                    .addComponent(txtEmail2)
                    .addGroup(painel4Layout.createSequentialGroup()
                        .addComponent(txtCep2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar2))
                    .addComponent(txtCidade2)
                    .addComponent(txtBairro2)
                    .addComponent(txtEndereco2)
                    .addComponent(txtNumero2)
                    .addComponent(txtComplemento2)
                    .addGroup(painel4Layout.createSequentialGroup()
                        .addGroup(painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRazao)
                            .addComponent(lblFantasia)
                            .addComponent(lblCnpj)
                            .addComponent(lblIe)
                            .addComponent(lblTelefone2)
                            .addComponent(lblEmail2)
                            .addComponent(lblCep2)
                            .addComponent(lblEstado2)
                            .addComponent(lblCidade2)
                            .addComponent(lblBairro2)
                            .addComponent(lblEndereco2)
                            .addComponent(lblNumero2)
                            .addComponent(lblComplemento2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtIe))
                .addContainerGap())
        );
        painel4Layout.setVerticalGroup(
            painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRazao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFantasia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCnpj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelefone2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCep2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstado2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCidade2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBairro2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBairro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndereco2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumero2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComplemento2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComplemento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        scroll2.setViewportView(painel4);

        pnlJuridica.add(scroll2, java.awt.BorderLayout.CENTER);

        painel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        btnAdicionar2.setText("Adicionar");
        btnAdicionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar2ActionPerformed(evt);
            }
        });
        painel5.add(btnAdicionar2);

        btnSair2.setText("Sair");
        btnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair2ActionPerformed(evt);
            }
        });
        painel5.add(btnSair2);

        pnlJuridica.add(painel5, java.awt.BorderLayout.SOUTH);

        tabbed.addTab("Jurídica", pnlJuridica);

        painel1.add(tabbed, java.awt.BorderLayout.CENTER);

        faixa2.setBackground(new java.awt.Color(44, 62, 80));

        javax.swing.GroupLayout faixa2Layout = new javax.swing.GroupLayout(faixa2);
        faixa2.setLayout(faixa2Layout);
        faixa2Layout.setHorizontalGroup(
            faixa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        faixa2Layout.setVerticalGroup(
            faixa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(faixa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(faixa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(faixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faixa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar1ActionPerformed

        if (!txtCep1.getText().trim().equals("")) {

            Endereco endereco = CEP.getEndereco(txtCep1.getText().trim());

            if (endereco != null) {
                cbxEstado1.setSelectedItem(endereco.getEstado());
                txtCidade1.setText(endereco.getCidade());
                txtBairro1.setText(endereco.getBairro());
                txtEndereco1.setText(endereco.getEndereco());
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível obter o endereço.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Informe um CEP.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisar1ActionPerformed

    private void btnAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar1ActionPerformed
        try {

            clienteJuridica = null;
            clienteFisica = new Fisica();

            clienteFisica.setNome(txtNome.getText().trim());
            clienteFisica.setCpf(txtCpf.getText().trim());
            clienteFisica.setRg(txtRg.getText().trim());
            clienteFisica.setTelefone(txtTelefone1.getText().trim());
            clienteFisica.setEmail(txtEmail1.getText().trim());
            clienteFisica.setEndereco(new Endereco(txtCep1.getText().trim(), cbxEstado1.getSelectedItem().toString(), txtCidade1.getText().trim(), txtBairro1.getText().trim(), txtEndereco1.getText().trim(), Integer.parseInt((txtNumero1.getText().trim().equals("") ? "0" : txtNumero1.getText())), txtComplemento1.getText().trim()));

            if (txtNascimento.getDate() != null) {
                clienteFisica.setDataNascimento(txtNascimento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            }

            fisicaService.save(clienteFisica);
            limparFormularioFisica();

            if (fechar) {
                sair();
            } else {
                JOptionPane.showMessageDialog(this, "Cliente adicionado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Informe um número válido!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdicionar1ActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair1ActionPerformed
        sair();
    }//GEN-LAST:event_btnSair1ActionPerformed

    private void btnPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar2ActionPerformed

        if (!txtCep2.getText().trim().equals("")) {

            Endereco endereco = CEP.getEndereco(txtCep2.getText().trim());

            if (endereco != null) {
                cbxEstado2.setSelectedItem(endereco.getEstado());
                txtCidade2.setText(endereco.getCidade());
                txtBairro2.setText(endereco.getBairro());
                txtEndereco2.setText(endereco.getEndereco());
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível obter o endereço.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Informe um CEP.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisar2ActionPerformed

    private void btnAdicionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar2ActionPerformed
        try {

            clienteFisica = null;
            clienteJuridica = new Juridica();

            clienteJuridica.setRazaoSocial(txtRazao.getText().trim());
            clienteJuridica.setNome(txtFantasia.getText().trim());
            clienteJuridica.setCnpj(txtCnpj.getText().trim());
            clienteJuridica.setInscricaoEstadual(txtIe.getText().trim());
            clienteJuridica.setTelefone(txtTelefone2.getText().trim());
            clienteJuridica.setEmail(txtEmail2.getText().trim());
            clienteJuridica.setEndereco(new Endereco(txtCep2.getText().trim(), cbxEstado2.getSelectedItem().toString(), txtCidade2.getText().trim(), txtBairro2.getText().trim(), txtEndereco2.getText().trim(), Integer.parseInt((txtNumero2.getText().trim().equals("") ? "0" : txtNumero2.getText())), txtComplemento2.getText().trim()));

            juridicaService.save(clienteJuridica);
            limparFormularioJuridica();

            if (fechar) {
                sair();
            }

            JOptionPane.showMessageDialog(this, "Cliente adicionado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Informe um número válido!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdicionar2ActionPerformed

    private void btnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair2ActionPerformed
        sair();
    }//GEN-LAST:event_btnSair2ActionPerformed

    /**
     * Limpa formulário do cliente pessoa física.
     */
    private void limparFormularioFisica() {
        txtNome.setText("");
        txtCpf.setText("");
        txtRg.setText("");
        txtNascimento.setDate(null);
        txtTelefone1.setText("");
        txtEmail1.setText("");
        txtCep1.setText("");
        cbxEstado1.setSelectedIndex(0);
        txtCidade1.setText("");
        txtBairro1.setText("");
        txtEndereco1.setText("");
        txtNumero1.setText("");
        txtComplemento1.setText("");
    }

    /**
     * Limpa formulário do cliente pessoa jurídica.
     */
    private void limparFormularioJuridica() {
        txtRazao.setText("");
        txtFantasia.setText("");
        txtCnpj.setText("");
        txtIe.setText("");
        txtTelefone2.setText("");
        txtEmail2.setText("");
        txtCep2.setText("");
        cbxEstado2.setSelectedIndex(0);
        txtCidade2.setText("");
        txtBairro2.setText("");
        txtEndereco2.setText("");
        txtNumero2.setText("");
        txtComplemento2.setText("");
    }

    /**
     * Fecha formulário.
     */
    private void sair() {
        setVisible(true);
        dispose();
    }

    /**
     * Seleciona aba de cliente pessoa física.
     */
    public void selecionarFisica() {
        tabbed.setSelectedIndex(0);
    }

    /**
     * Seleciona aba de cliente pessoa jurídica.
     */
    public void selecionarJuridica() {
        tabbed.setSelectedIndex(1);
    }

    public Cliente getCliente() {
        if (tabbed.getSelectedIndex() == 0) {
            return clienteFisica;
        } else {
            return clienteJuridica;
        }
    }

    public void setFechar(boolean fechar) {
        this.fechar = fechar;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarClienteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar1;
    private javax.swing.JButton btnAdicionar2;
    private javax.swing.JButton btnPesquisar1;
    private javax.swing.JButton btnPesquisar2;
    private javax.swing.JButton btnSair1;
    private javax.swing.JButton btnSair2;
    private javax.swing.JComboBox<String> cbxEstado1;
    private javax.swing.JComboBox<String> cbxEstado2;
    private javax.swing.JPanel faixa1;
    private javax.swing.JPanel faixa2;
    private javax.swing.JLabel lblBairro1;
    private javax.swing.JLabel lblBairro2;
    private javax.swing.JLabel lblCep1;
    private javax.swing.JLabel lblCep2;
    private javax.swing.JLabel lblCidade1;
    private javax.swing.JLabel lblCidade2;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblComplemento1;
    private javax.swing.JLabel lblComplemento2;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblEndereco1;
    private javax.swing.JLabel lblEndereco2;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblFantasia;
    private javax.swing.JLabel lblIe;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero1;
    private javax.swing.JLabel lblNumero2;
    private javax.swing.JLabel lblRazao;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblTelefone1;
    private javax.swing.JLabel lblTelefone2;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painel3;
    private javax.swing.JPanel painel4;
    private javax.swing.JPanel painel5;
    private javax.swing.JPanel pnlFisica;
    private javax.swing.JPanel pnlJuridica;
    private javax.swing.JScrollPane scroll1;
    private javax.swing.JScrollPane scroll2;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtBairro1;
    private javax.swing.JTextField txtBairro2;
    private javax.swing.JTextField txtCep1;
    private javax.swing.JTextField txtCep2;
    private javax.swing.JTextField txtCidade1;
    private javax.swing.JTextField txtCidade2;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtComplemento1;
    private javax.swing.JTextField txtComplemento2;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtEndereco1;
    private javax.swing.JTextField txtEndereco2;
    private javax.swing.JTextField txtFantasia;
    private javax.swing.JTextField txtIe;
    private com.toedter.calendar.JDateChooser txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtRazao;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtTelefone1;
    private javax.swing.JTextField txtTelefone2;
    // End of variables declaration//GEN-END:variables
}
