package br.unesp.locadora.gui.cliente;

import br.unesp.locadora.gui.util.JTableUtil;
import br.unesp.locadora.model.Fisica;
import br.unesp.locadora.model.Juridica;
import br.unesp.locadora.service.FisicaService;
import br.unesp.locadora.service.JuridicaService;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class ClientesForm extends javax.swing.JFrame {

    /**
     * Serviço de persistência de clientes pessoa física.
     */
    FisicaService fisicaService = new FisicaService();

    /**
     * Serviço de persistência de clientes pessoa jurídica.
     */
    JuridicaService juridicaService = new JuridicaService();

    /**
     * Creates new form ClientesForm
     */
    public ClientesForm() {
        initComponents();
        atualizarTabelas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        faixa1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        painel1 = new javax.swing.JPanel();
        tabbed = new javax.swing.JTabbedPane();
        pnlFisica = new javax.swing.JPanel();
        painel2 = new javax.swing.JPanel();
        scroll1 = new javax.swing.JScrollPane();
        tblFisica = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAtualizar1 = new javax.swing.JButton();
        btnPesquisar1 = new javax.swing.JButton();
        btnAdicionar1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnExcluir1 = new javax.swing.JButton();
        btnSair1 = new javax.swing.JButton();
        pnlJuridica = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        scroll2 = new javax.swing.JScrollPane();
        tblJuridica = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAtualizar2 = new javax.swing.JButton();
        btnPesquisar2 = new javax.swing.JButton();
        btnAdicionar2 = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();
        btnExcluir2 = new javax.swing.JButton();
        btnSair2 = new javax.swing.JButton();
        faixa2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        setExtendedState(6);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));

        faixa1.setBackground(new java.awt.Color(44, 62, 80));

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/title_clientes.png"))); // NOI18N

        javax.swing.GroupLayout faixa1Layout = new javax.swing.GroupLayout(faixa1);
        faixa1.setLayout(faixa1Layout);
        faixa1Layout.setHorizontalGroup(
            faixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        faixa1Layout.setVerticalGroup(
            faixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        painel1.setLayout(new java.awt.BorderLayout());

        pnlFisica.setLayout(new java.awt.BorderLayout());

        painel2.setLayout(new java.awt.BorderLayout());

        scroll1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scroll1MouseClicked(evt);
            }
        });

        tblFisica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "RG", "Nascimento", "Telefone", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFisica.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblFisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFisicaMouseClicked(evt);
            }
        });
        scroll1.setViewportView(tblFisica);

        painel2.add(scroll1, java.awt.BorderLayout.CENTER);

        pnlFisica.add(painel2, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        btnAtualizar1.setText("Atualizar");
        btnAtualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAtualizar1);

        btnPesquisar1.setText("Pesquisar");
        btnPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPesquisar1);

        btnAdicionar1.setText("Adicionar");
        btnAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdicionar1);

        btnEditar1.setText("Editar");
        btnEditar1.setEnabled(false);
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar1);

        btnExcluir1.setText("Excluir");
        btnExcluir1.setEnabled(false);
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnExcluir1);

        btnSair1.setText("Sair");
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSair1);

        pnlFisica.add(jPanel2, java.awt.BorderLayout.SOUTH);

        tabbed.addTab("Física", pnlFisica);

        pnlJuridica.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        scroll2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scroll2MouseClicked(evt);
            }
        });

        tblJuridica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Razão Social", "Nome Fantasia", "CNPJ", "IE", "Telefone", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblJuridica.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblJuridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJuridicaMouseClicked(evt);
            }
        });
        scroll2.setViewportView(tblJuridica);

        jPanel3.add(scroll2, java.awt.BorderLayout.CENTER);

        pnlJuridica.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        btnAtualizar2.setText("Atualizar");
        btnAtualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizar2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnAtualizar2);

        btnPesquisar2.setText("Pesquisar");
        btnPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnPesquisar2);

        btnAdicionar2.setText("Adicionar");
        btnAdicionar2.setToolTipText("");
        btnAdicionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdicionar2);

        btnEditar2.setText("Editar");
        btnEditar2.setEnabled(false);
        btnEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditar2);

        btnExcluir2.setText("Excluir");
        btnExcluir2.setEnabled(false);
        btnExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnExcluir2);

        btnSair2.setText("Sair");
        btnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSair2);

        pnlJuridica.add(jPanel4, java.awt.BorderLayout.SOUTH);

        tabbed.addTab("Jurídica", pnlJuridica);

        painel1.add(tabbed, java.awt.BorderLayout.CENTER);

        faixa2.setBackground(new java.awt.Color(44, 62, 80));

        javax.swing.GroupLayout faixa2Layout = new javax.swing.GroupLayout(faixa2);
        faixa2.setLayout(faixa2Layout);
        faixa2Layout.setHorizontalGroup(
            faixa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        faixa2Layout.setVerticalGroup(
            faixa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(faixa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(faixa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(faixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faixa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizar1ActionPerformed
        atualizarTabelaFisica();
    }//GEN-LAST:event_btnAtualizar1ActionPerformed

    private void btnPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar1ActionPerformed

        PesquisarFisicaForm form = new PesquisarFisicaForm();

        form.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent evt) {
                if (form.getResultado() != null) {
                    atualizarTabelaFisica(form.getResultado());
                }
            }

        });

        form.setVisible(true);
    }//GEN-LAST:event_btnPesquisar1ActionPerformed

    private void btnAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar1ActionPerformed

        AdicionarClienteForm form = new AdicionarClienteForm();

        form.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent evt) {
                atualizarTabelaFisica();
            }

        });

        form.selecionarFisica();
        form.setVisible(true);
    }//GEN-LAST:event_btnAdicionar1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed

        if (idLinhaSelecionada(tblFisica) != -1) {

            EditarClienteForm form = new EditarClienteForm();

            form.addWindowListener(new WindowAdapter() {

                @Override
                public void windowClosed(WindowEvent evt) {
                    atualizarTabelaFisica();
                }

            });

            form.setIdFisica(idLinhaSelecionada(tblFisica));
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
        if (idLinhaSelecionada(tblFisica) != -1) {
            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o cliente selecionado?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    fisicaService.delete(fisicaService.getById(idLinhaSelecionada(tblFisica)));
                    removerLinhaSelecionada(tblFisica);
                    removerSelecaoFisica();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnExcluir1ActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair1ActionPerformed
        sair();
    }//GEN-LAST:event_btnSair1ActionPerformed

    private void btnAtualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizar2ActionPerformed
        atualizarTabelaJuridica();
    }//GEN-LAST:event_btnAtualizar2ActionPerformed

    private void btnPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar2ActionPerformed

        PesquisarJuridicaForm form = new PesquisarJuridicaForm();

        form.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent evt) {
                if (form.getResultado() != null) {
                    atualizarTabelaJuridica(form.getResultado());
                }
            }

        });

        form.setVisible(true);
    }//GEN-LAST:event_btnPesquisar2ActionPerformed

    private void btnAdicionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar2ActionPerformed

        AdicionarClienteForm form = new AdicionarClienteForm();

        form.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent evt) {
                atualizarTabelaJuridica();
            }

        });

        form.selecionarJuridica();
        form.setVisible(true);
    }//GEN-LAST:event_btnAdicionar2ActionPerformed

    private void btnEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar2ActionPerformed

        if (idLinhaSelecionada(tblJuridica) != -1) {

            EditarClienteForm form = new EditarClienteForm();

            form.addWindowListener(new WindowAdapter() {

                @Override
                public void windowClosed(WindowEvent evt) {
                    atualizarTabelaJuridica();
                }

            });

            form.setIdJuridica(idLinhaSelecionada(tblJuridica));
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnEditar2ActionPerformed

    private void btnExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir2ActionPerformed
        if (idLinhaSelecionada(tblJuridica) != -1) {
            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o cliente selecionado?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    juridicaService.delete(juridicaService.getById(idLinhaSelecionada(tblJuridica)));
                    removerLinhaSelecionada(tblJuridica);
                    removerSelecaoJuridica();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnExcluir2ActionPerformed

    private void btnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair2ActionPerformed
        sair();
    }//GEN-LAST:event_btnSair2ActionPerformed

    private void tblFisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFisicaMouseClicked

        if (tblFisica.rowAtPoint(evt.getPoint()) > -1) {
            btnEditar1.setEnabled(true);
            btnExcluir1.setEnabled(true);
        }

        if (evt.getClickCount() == 2) {
            btnEditar1ActionPerformed(null);
        }
    }//GEN-LAST:event_tblFisicaMouseClicked

    private void scroll1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scroll1MouseClicked
        removerSelecaoFisica();
    }//GEN-LAST:event_scroll1MouseClicked

    private void tblJuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJuridicaMouseClicked

        if (tblJuridica.rowAtPoint(evt.getPoint()) > -1) {
            btnEditar2.setEnabled(true);
            btnExcluir2.setEnabled(true);
        }

        if (evt.getClickCount() == 2) {
            btnEditar2ActionPerformed(null);
        }
    }//GEN-LAST:event_tblJuridicaMouseClicked

    private void scroll2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scroll2MouseClicked
        removerSelecaoJuridica();
    }//GEN-LAST:event_scroll2MouseClicked

    /**
     * Fecha formulário.
     */
    private void sair() {
        setVisible(true);
        dispose();
    }

    /**
     * Remove seleção da tabela de clientes pessoa física.
     */
    private void removerSelecaoFisica() {
        tblFisica.clearSelection();
        btnEditar1.setEnabled(false);
        btnExcluir1.setEnabled(false);
    }

    /**
     * Remove seleção da tabela de clientes pessoa jurídica.
     */
    private void removerSelecaoJuridica() {
        tblJuridica.clearSelection();
        btnEditar2.setEnabled(false);
        btnExcluir2.setEnabled(false);
    }

    /**
     * Atualiza dados da tabela de clientes pessoa física.
     *
     * @param dados Dados.
     */
    private void atualizarTabelaFisica(List<Fisica> dados) {
        JTableUtil.fillClientesFisica(tblFisica, dados);
        removerSelecaoFisica();
    }

    /**
     * Atualiza dados da tabela de clientes pessoa física.
     */
    private void atualizarTabelaFisica() {
        atualizarTabelaFisica(fisicaService.list());
    }

    /**
     * Atualiza dados da tabela de clientes pessoa jurídica.
     *
     * @param dados Dados.
     */
    private void atualizarTabelaJuridica(List<Juridica> dados) {
        JTableUtil.fillClientesJuridica(tblJuridica, dados);
        removerSelecaoJuridica();
    }

    /**
     * Atualiza dados da tabela de clientes pessoa jurídica.
     */
    private void atualizarTabelaJuridica() {
        atualizarTabelaJuridica(juridicaService.list());
    }

    /**
     * Atualiza dados das tabelas.
     */
    private void atualizarTabelas() {
        atualizarTabelaFisica();
        atualizarTabelaJuridica();
    }

    /**
     * Retorna ID do cliente selecionado.
     *
     * @param jTable JTable.
     * @return ID do cliente.
     */
    private int idLinhaSelecionada(JTable jTable) {

        int id = -1;

        if (jTable.getSelectedRow() != -1) {
            id = Integer.parseInt(jTable.getModel().getValueAt(jTable.getSelectedRow(), 0).toString());
        }

        return id;
    }

    /**
     * Remove linha selecionada da tabela.
     *
     * @param jTable JTable.
     */
    private void removerLinhaSelecionada(JTable jTable) {
        JTableUtil.remove(jTable, jTable.getSelectedRow());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar1;
    private javax.swing.JButton btnAdicionar2;
    private javax.swing.JButton btnAtualizar1;
    private javax.swing.JButton btnAtualizar2;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEditar2;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnExcluir2;
    private javax.swing.JButton btnPesquisar1;
    private javax.swing.JButton btnPesquisar2;
    private javax.swing.JButton btnSair1;
    private javax.swing.JButton btnSair2;
    private javax.swing.JPanel faixa1;
    private javax.swing.JPanel faixa2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel pnlFisica;
    private javax.swing.JPanel pnlJuridica;
    private javax.swing.JScrollPane scroll1;
    private javax.swing.JScrollPane scroll2;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTable tblFisica;
    private javax.swing.JTable tblJuridica;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
