package br.unesp.locadora.gui.pedido;

import br.unesp.locadora.gui.util.JTableUtil;
import br.unesp.locadora.model.Pedido;
import br.unesp.locadora.service.PedidoService;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class PedidosForm extends javax.swing.JFrame {

    /**
     * Serviço de persistência de pedidos.
     */
    PedidoService pedidoService = new PedidoService();

    /**
     * Creates new form PedidosForm
     */
    public PedidosForm() {
        initComponents();
        atualizarTabelas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        faixa1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        painel1 = new javax.swing.JPanel();
        tabbed = new javax.swing.JTabbedPane();
        painel2 = new javax.swing.JPanel();
        scroll1 = new javax.swing.JScrollPane();
        tblAtivos = new javax.swing.JTable();
        painel3 = new javax.swing.JPanel();
        btnAtualizar1 = new javax.swing.JButton();
        btnPesquisar1 = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSair1 = new javax.swing.JButton();
        painel4 = new javax.swing.JPanel();
        scroll2 = new javax.swing.JScrollPane();
        tblFinalizados = new javax.swing.JTable();
        painel5 = new javax.swing.JPanel();
        btnAtualizar2 = new javax.swing.JButton();
        btnPesquisar2 = new javax.swing.JButton();
        btnVisualizar2 = new javax.swing.JButton();
        btnSair2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        scroll3 = new javax.swing.JScrollPane();
        tblCancelados = new javax.swing.JTable();
        paniel7 = new javax.swing.JPanel();
        btnAtualizar3 = new javax.swing.JButton();
        btnPesquisar3 = new javax.swing.JButton();
        btnVisualizar3 = new javax.swing.JButton();
        btnSair3 = new javax.swing.JButton();
        faixa2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedidos");
        setExtendedState(6);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));

        faixa1.setBackground(new java.awt.Color(44, 62, 80));

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/title_pedidos.png"))); // NOI18N

        javax.swing.GroupLayout faixa1Layout = new javax.swing.GroupLayout(faixa1);
        faixa1.setLayout(faixa1Layout);
        faixa1Layout.setHorizontalGroup(
            faixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        faixa1Layout.setVerticalGroup(
            faixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        painel1.setLayout(new java.awt.BorderLayout());

        painel2.setLayout(new java.awt.BorderLayout());

        scroll1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scroll1MouseClicked(evt);
            }
        });

        tblAtivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Veículo", "Cliente", "Retirada", "Devolução", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAtivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAtivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAtivosMouseClicked(evt);
            }
        });
        scroll1.setViewportView(tblAtivos);

        painel2.add(scroll1, java.awt.BorderLayout.CENTER);

        painel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        btnAtualizar1.setText("Atualizar");
        btnAtualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizar1ActionPerformed(evt);
            }
        });
        painel3.add(btnAtualizar1);

        btnPesquisar1.setText("Pesquisar");
        btnPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar1ActionPerformed(evt);
            }
        });
        painel3.add(btnPesquisar1);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        painel3.add(btnAdicionar);

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        painel3.add(btnEditar);

        btnFinalizar.setText("Finalizar");
        btnFinalizar.setEnabled(false);
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        painel3.add(btnFinalizar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painel3.add(btnCancelar);

        btnSair1.setText("Sair");
        btnSair1.setToolTipText("");
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });
        painel3.add(btnSair1);

        painel2.add(painel3, java.awt.BorderLayout.SOUTH);

        tabbed.addTab("Ativos", painel2);

        painel4.setLayout(new java.awt.BorderLayout());

        scroll2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scroll2MouseClicked(evt);
            }
        });

        tblFinalizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Veículo", "Cliente", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFinalizados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblFinalizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFinalizadosMouseClicked(evt);
            }
        });
        scroll2.setViewportView(tblFinalizados);

        painel4.add(scroll2, java.awt.BorderLayout.CENTER);

        painel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        btnAtualizar2.setText("Atualizar");
        btnAtualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizar2ActionPerformed(evt);
            }
        });
        painel5.add(btnAtualizar2);

        btnPesquisar2.setText("Pesquisar");
        btnPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar2ActionPerformed(evt);
            }
        });
        painel5.add(btnPesquisar2);

        btnVisualizar2.setText("Visualizar");
        btnVisualizar2.setEnabled(false);
        btnVisualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizar2ActionPerformed(evt);
            }
        });
        painel5.add(btnVisualizar2);

        btnSair2.setText("Sair");
        btnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair2ActionPerformed(evt);
            }
        });
        painel5.add(btnSair2);

        painel4.add(painel5, java.awt.BorderLayout.SOUTH);

        tabbed.addTab("Finalizados", painel4);

        jPanel6.setLayout(new java.awt.BorderLayout());

        scroll3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scroll3MouseClicked(evt);
            }
        });

        tblCancelados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Veículo", "Cliente", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCancelados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCancelados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCanceladosMouseClicked(evt);
            }
        });
        scroll3.setViewportView(tblCancelados);

        jPanel6.add(scroll3, java.awt.BorderLayout.CENTER);

        paniel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        btnAtualizar3.setText("Atualizar");
        btnAtualizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizar3ActionPerformed(evt);
            }
        });
        paniel7.add(btnAtualizar3);

        btnPesquisar3.setText("Pesquisar");
        btnPesquisar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar3ActionPerformed(evt);
            }
        });
        paniel7.add(btnPesquisar3);

        btnVisualizar3.setText("Visualizar");
        btnVisualizar3.setEnabled(false);
        btnVisualizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizar3ActionPerformed(evt);
            }
        });
        paniel7.add(btnVisualizar3);

        btnSair3.setText("Sair");
        btnSair3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair3ActionPerformed(evt);
            }
        });
        paniel7.add(btnSair3);

        jPanel6.add(paniel7, java.awt.BorderLayout.PAGE_END);

        tabbed.addTab("Cancelados", jPanel6);

        painel1.add(tabbed, java.awt.BorderLayout.CENTER);
        tabbed.getAccessibleContext().setAccessibleName("");

        faixa2.setBackground(new java.awt.Color(44, 62, 80));

        javax.swing.GroupLayout faixa2Layout = new javax.swing.GroupLayout(faixa2);
        faixa2.setLayout(faixa2Layout);
        faixa2Layout.setHorizontalGroup(
            faixa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        faixa2Layout.setVerticalGroup(
            faixa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(faixa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(faixa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(faixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faixa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizar1ActionPerformed
        atualizarTabelaAtivos();
    }//GEN-LAST:event_btnAtualizar1ActionPerformed

    private void btnPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar1ActionPerformed

        PesquisarAtivosForm form = new PesquisarAtivosForm();

        form.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent evt) {
                if (form.getResultado() != null) {
                    atualizarTabelaAtivos(form.getResultado());
                }
            }

        });

        form.setVisible(true);
    }//GEN-LAST:event_btnPesquisar1ActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        AdicionarPedidoForm form = new AdicionarPedidoForm();

        form.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent evt) {
                atualizarTabelaAtivos();
            }

        });

        form.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (idLinhaSelecionada(tblAtivos) != -1) {

            EditarPedidoForm form = new EditarPedidoForm();

            form.addWindowListener(new WindowAdapter() {

                @Override
                public void windowClosed(WindowEvent evt) {
                    atualizarTabelaAtivos();
                }

            });

            form.setId(idLinhaSelecionada(tblAtivos));
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        if (idLinhaSelecionada(tblAtivos) != -1) {

            FinalizarPedidoForm form = new FinalizarPedidoForm();

            form.addWindowListener(new WindowAdapter() {

                @Override
                public void windowClosed(WindowEvent evt) {
                    atualizarTabelaAtivos();
                    atualizarTabelaFinalizados();
                }

            });

            form.setId(idLinhaSelecionada(tblAtivos));
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (idLinhaSelecionada(tblAtivos) != -1) {
            if (JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar o pedido selecionado?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {

                    Pedido pedido = pedidoService.getById(idLinhaSelecionada(tblAtivos));
                    pedido.cancelar();

                    pedidoService.save(pedido);

                    removerLinhaSelecionada(tblAtivos);
                    removerSelecaoAtivos();
                    atualizarTabelaCancelados();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair1ActionPerformed
        sair();
    }//GEN-LAST:event_btnSair1ActionPerformed

    private void btnAtualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizar2ActionPerformed
        atualizarTabelaFinalizados();
    }//GEN-LAST:event_btnAtualizar2ActionPerformed

    private void btnPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar2ActionPerformed

        PesquisarFinalizadosForm form = new PesquisarFinalizadosForm();

        form.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent evt) {
                if (form.getResultado() != null) {
                    atualizarTabelaFinalizados(form.getResultado());
                }
            }

        });

        form.setVisible(true);
    }//GEN-LAST:event_btnPesquisar2ActionPerformed

    private void btnVisualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizar2ActionPerformed

        if (idLinhaSelecionada(tblFinalizados) != -1) {

            VisualizarPedidoForm form = new VisualizarPedidoForm();

            form.setId(idLinhaSelecionada(tblFinalizados));
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnVisualizar2ActionPerformed

    private void btnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair2ActionPerformed
        sair();
    }//GEN-LAST:event_btnSair2ActionPerformed

    private void btnAtualizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizar3ActionPerformed
        atualizarTabelaCancelados();
    }//GEN-LAST:event_btnAtualizar3ActionPerformed

    private void btnPesquisar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar3ActionPerformed

        PesquisarCanceladosForm form = new PesquisarCanceladosForm();

        form.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent evt) {
                if (form.getResultado() != null) {
                    atualizarTabelaCancelados(form.getResultado());
                }
            }

        });

        form.setVisible(true);
    }//GEN-LAST:event_btnPesquisar3ActionPerformed

    private void btnVisualizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizar3ActionPerformed

        if (idLinhaSelecionada(tblCancelados) != -1) {

            VisualizarPedidoForm form = new VisualizarPedidoForm();

            form.setId(idLinhaSelecionada(tblCancelados));
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnVisualizar3ActionPerformed

    private void btnSair3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair3ActionPerformed
        sair();
    }//GEN-LAST:event_btnSair3ActionPerformed

    private void tblAtivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAtivosMouseClicked

        if (tblFinalizados.rowAtPoint(evt.getPoint()) > -1) {
            btnEditar.setEnabled(true);
            btnFinalizar.setEnabled(true);
            btnCancelar.setEnabled(true);
        }

        if (evt.getClickCount() == 2) {
            btnEditarActionPerformed(null);
        }
    }//GEN-LAST:event_tblAtivosMouseClicked

    private void scroll1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scroll1MouseClicked
        removerSelecaoAtivos();
    }//GEN-LAST:event_scroll1MouseClicked

    private void tblFinalizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFinalizadosMouseClicked

        if (tblFinalizados.rowAtPoint(evt.getPoint()) > -1) {
            btnVisualizar2.setEnabled(true);
        }

        if (evt.getClickCount() == 2) {
            btnVisualizar2ActionPerformed(null);
        }
    }//GEN-LAST:event_tblFinalizadosMouseClicked

    private void scroll2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scroll2MouseClicked
        removerSelecaoFinalizados();
    }//GEN-LAST:event_scroll2MouseClicked

    private void tblCanceladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCanceladosMouseClicked

        if (tblFinalizados.rowAtPoint(evt.getPoint()) > -1) {
            btnVisualizar3.setEnabled(true);
        }

        if (evt.getClickCount() == 2) {
            btnVisualizar3ActionPerformed(null);
        }
    }//GEN-LAST:event_tblCanceladosMouseClicked

    private void scroll3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scroll3MouseClicked
        removerSelecaoCancelados();
    }//GEN-LAST:event_scroll3MouseClicked

    /**
     * Fecha formulário.
     */
    private void sair() {
        setVisible(false);
        dispose();
    }

    /**
     * Remove seleção da tabela de pedidos ativos.
     */
    private void removerSelecaoAtivos() {
        tblAtivos.clearSelection();
        btnEditar.setEnabled(false);
        btnFinalizar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }

    /**
     * Remove seleção da tabela de pedidos finalizados.
     */
    private void removerSelecaoFinalizados() {
        tblFinalizados.clearSelection();
        btnVisualizar2.setEnabled(false);
    }

    /**
     * Remove seleção da tabela de pedidos cancelados.
     */
    private void removerSelecaoCancelados() {
        tblCancelados.clearSelection();
        btnVisualizar3.setEnabled(false);
    }

    /**
     * Atualiza dados da tabela de pedidos ativos.
     *
     * @param dados Dados.
     */
    private void atualizarTabelaAtivos(List<Pedido> dados) {
        JTableUtil.fillPedidos(tblAtivos, dados, true);
        removerSelecaoAtivos();
    }

    /**
     * Atualiza dados da tabela de pedidos ativos.
     */
    private void atualizarTabelaAtivos() {
        atualizarTabelaAtivos(pedidoService.listAtivos());
    }

    /**
     * Atualiza dados da tabela de pedidos finalizados.
     *
     * @param dados Dados.
     */
    private void atualizarTabelaFinalizados(List<Pedido> dados) {
        JTableUtil.fillPedidos(tblFinalizados, dados, false);
        removerSelecaoFinalizados();
    }

    /**
     * Atualiza dados da tabela de pedidos finalizados.
     */
    private void atualizarTabelaFinalizados() {
        atualizarTabelaFinalizados(pedidoService.listFinalizados());
    }

    /**
     * Atualiza dados da tabela de pedidos cancelados.
     *
     * @param dados Dados.
     */
    private void atualizarTabelaCancelados(List<Pedido> dados) {
        JTableUtil.fillPedidos(tblCancelados, dados, false);
        removerSelecaoCancelados();
    }

    /**
     * Atualiza dados da tabela de pedidos cancelados.
     */
    private void atualizarTabelaCancelados() {
        atualizarTabelaCancelados(pedidoService.listCancelados());
    }

    /**
     * Atualiza dados das tabelas.
     */
    private void atualizarTabelas() {
        atualizarTabelaAtivos();
        atualizarTabelaFinalizados();
        atualizarTabelaCancelados();
    }

    /**
     * Retorna ID do pedido selecionado.
     *
     * @param jTable JTable.
     * @return ID do cliente.
     */
    private int idLinhaSelecionada(JTable jTable) {

        int id = -1;

        if (jTable.getSelectedRow() != -1) {
            id = Integer.parseInt(jTable.getModel().getValueAt(jTable.getSelectedRow(), 0).toString());
        }

        return id;
    }

    /**
     * Remove linha selecionada da tabela.
     *
     * @param jTable JTable.
     */
    private void removerLinhaSelecionada(JTable jTable) {
        JTableUtil.remove(jTable, jTable.getSelectedRow());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar1;
    private javax.swing.JButton btnAtualizar2;
    private javax.swing.JButton btnAtualizar3;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnPesquisar1;
    private javax.swing.JButton btnPesquisar2;
    private javax.swing.JButton btnPesquisar3;
    private javax.swing.JButton btnSair1;
    private javax.swing.JButton btnSair2;
    private javax.swing.JButton btnSair3;
    private javax.swing.JButton btnVisualizar2;
    private javax.swing.JButton btnVisualizar3;
    private javax.swing.JPanel faixa1;
    private javax.swing.JPanel faixa2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painel3;
    private javax.swing.JPanel painel4;
    private javax.swing.JPanel painel5;
    private javax.swing.JPanel paniel7;
    private javax.swing.JScrollPane scroll1;
    private javax.swing.JScrollPane scroll2;
    private javax.swing.JScrollPane scroll3;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTable tblAtivos;
    private javax.swing.JTable tblCancelados;
    private javax.swing.JTable tblFinalizados;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
